### PR TITLE
Updated changes from odin-detector repo

### PR DESCRIPTION
**Pull request by MattTaylorDLS**

### CODE REVIEW

**Comment by GDYendell** [comment]
Why are we not just fast-forwarding to odin-detector/master?

**Comment by ajgdls** [comment]
Agreed this probably shouldn't be a merge as we would eventually just end up with many unnecessary merge commits in the history.

**Comment by MattTaylorDLS** [comment]
Ah, i thought Github would be clever enough to work that out when using one of the options from the 'Merge' dropdown.

**Comment by GDYendell** [comment]
Possibly. I don't know that this will rebase nicely, though, because of the re-creating of parts of commits on odin-detector/master. Not sure what GitHub will do with that.

**Comment by MattTaylorDLS** [comment]
ok. should just do a fast forward then.

If we want to cherry pick this into the GDA integration branch, are there other changes we want as well? (i.e. just take everything from Master), or just take then ones we actually need ?

**Comment by ajgdls** [comment]
I think the way to do it would be to rebase GDA against master taking all master commits.  We should keep up with master where at all possible otherwise it becomes harder to manage as branches diverge.  That's only my opinion of course :)

**Pull request merged**
